#!/bin/sh
#
# @name Fighter VTOL
#
# @type Standard VTOL
#

. ${R}etc/init.d/rc.vtol_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=fighter_vtol}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_ARSPDSIM 1
param set-default SENS_EN_MAGSIM 1

# Sensor calibration for HITL (bypass calibration checks)
# Accelerometer
param set-default CAL_ACC0_ID 1310988
param set-default CAL_ACC0_XOFF 0.0
param set-default CAL_ACC0_YOFF 0.0
param set-default CAL_ACC0_ZOFF 0.0
param set-default CAL_ACC0_XSCALE 1.0
param set-default CAL_ACC0_YSCALE 1.0
param set-default CAL_ACC0_ZSCALE 1.0

# Gyroscope
param set-default CAL_GYRO0_ID 1310988
param set-default CAL_GYRO0_XOFF 0.0
param set-default CAL_GYRO0_YOFF 0.0
param set-default CAL_GYRO0_ZOFF 0.0

# Magnetometer
param set-default CAL_MAG0_ID 197388
param set-default CAL_MAG0_XOFF 0.0
param set-default CAL_MAG0_YOFF 0.0
param set-default CAL_MAG0_ZOFF 0.0
param set-default CAL_MAG0_XSCALE 1.0
param set-default CAL_MAG0_YSCALE 1.0
param set-default CAL_MAG0_ZSCALE 1.0

param set-default FD_ACT_EN 0
param set-default FD_ACT_MOT_TOUT 500

param set-default CA_AIRFRAME 2

param set-default COM_PREARM_MODE 2

# Rotor configuration (4 MC + 1 pusher)
param set-default CA_ROTOR_COUNT 5

# Front right motor with -z spin
param set-default CA_ROTOR0_CT 85.0
param set-default CA_ROTOR0_KM 0.0205
param set-default CA_ROTOR0_PX 0.416
param set-default CA_ROTOR0_PY 0.504

# Rear left motor with -z spin
param set-default CA_ROTOR1_CT 85.0
param set-default CA_ROTOR1_KM 0.0205
param set-default CA_ROTOR1_PX -0.48
param set-default CA_ROTOR1_PY -0.50

# Front left motor with +z spin
param set-default CA_ROTOR2_CT 85.0
param set-default CA_ROTOR2_KM -0.0205
param set-default CA_ROTOR2_PX 0.42
param set-default CA_ROTOR2_PY -0.50

# Rear right motor with +z spin
param set-default CA_ROTOR3_CT 85.0
param set-default CA_ROTOR3_KM -0.0205
param set-default CA_ROTOR3_PX -0.48
param set-default CA_ROTOR3_PY 0.50

# Pusher motor with +x spin
param set-default CA_ROTOR4_CT 80.0
param set-default CA_ROTOR4_KM 0.0281
param set-default CA_ROTOR4_PX -1.026
param set-default CA_ROTOR4_AX 1
param set-default CA_ROTOR4_AY 0
param set-default CA_ROTOR4_AZ 0

# Motor outputs
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 10
param set-default SIM_GZ_EC_MAX1 1055
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 10
param set-default SIM_GZ_EC_MAX2 1055
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_MIN3 10
param set-default SIM_GZ_EC_MAX3 1055
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN4 10
param set-default SIM_GZ_EC_MAX4 1055

# Pusher motor
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_MIN5 0
param set-default SIM_GZ_EC_MAX5 826

# Servo outputs (5 control surfaces)
# Limit deflection range to prevent over-travel after damping removal
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_MIN1 -0.5
param set-default SIM_GZ_SV_MAX1 0.5
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_MIN2 -0.5
param set-default SIM_GZ_SV_MAX2 0.5
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_MIN3 -0.5
param set-default SIM_GZ_SV_MAX3 0.5
param set-default SIM_GZ_SV_FUNC4 204
param set-default SIM_GZ_SV_MIN4 -0.5
param set-default SIM_GZ_SV_MAX4 0.5
param set-default SIM_GZ_SV_FUNC5 205
param set-default SIM_GZ_SV_MIN5 -0.5
param set-default SIM_GZ_SV_MAX5 0.5

param set-default COM_RC_IN_MODE 1

# Control surface configuration
param set-default CA_SV_CS_COUNT 5
# Left aileron
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5
# Right aileron
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS1_TRQ_R 0.5
# Left elevator (inverted due to Gazebo joint direction)
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS2_TRQ_P -0.5
# Right elevator (inverted due to Gazebo joint direction)
param set-default CA_SV_CS3_TYPE 3
param set-default CA_SV_CS3_TRQ_P -0.5
# Rudder (inverted due to Gazebo joint direction)
param set-default CA_SV_CS4_TYPE 4
param set-default CA_SV_CS4_TRQ_Y -1

param set-default NPFG_PERIOD 12
param set-default FW_PR_FF 0.2
param set-default FW_PR_P 0.6
param set-default FW_PR_D 0.03
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MIN -15
param set-default FW_P_RMAX_POS 40
param set-default FW_P_RMAX_NEG 40
param set-default FW_R_RMAX 50
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3
param set-default FW_Y_RMAX 30
param set-default FW_THR_TRIM 0.25
param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2

# MC attitude control - increased gains for better transition stability
param set-default MC_AIRMODE 1
param set-default MC_ROLLRATE_P 0.5
param set-default MC_PITCHRATE_P 0.2
param set-default MC_YAW_P 1.6
param set-default MC_YAWRATE_MAX 30

param set-default MIS_TAKEOFF_ALT 10

param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_P_ACC 3
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_D_ACC 0.1
param set-default MPC_THR_HOVER 0.38

param set-default NAV_ACC_RAD 5
param set-default NAV_DLL_ACT 2

# VTOL transition parameters
param set-default VT_FWD_THRUST_EN 4
param set-default VT_F_TRANS_THR 0.75
param set-default VT_TYPE 2
param set-default VT_PITCH_MIN -5
param set-default VT_QC_T_ALT_LOSS 40
param set-default VT_ARSP_BLEND 8
param set-default VT_ARSP_TRANS 12

param set-default FD_ESCS_EN 0
