#!/bin/sh
#
# @name Fighter 4+1 VTOL (Makeflyeasy)
#
# @type Fighter 4+1 VTOL
#

# param reference: https://docs.px4.io/main/en/advanced_config/parameter_reference

. ${R}etc/init.d/rc.vtol_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=standard_vtol}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_ARSPDSIM 1

# TODO: Enable motor failure detection when the
# VTOL no longer reports 0A for all ESCs in SITL
param set-default FD_ACT_EN 0
param set-default FD_ACT_MOT_TOUT 500

param set-default CA_AIRFRAME 2 # standard_vtol

param set-default COM_PREARM_MODE 2
# Rotor config
param set-default CA_ROTOR_COUNT 5

# Important Note:
# Our CAD model is facing negative x axis, but gazebo's reference frame is facing positive x axis
# And PX4 seems is using the gazebo reference frame as the body frame (?), also PX4 is X forward, Y right, Z down
# This case the rotor0 is on the rear left ,
# rotor1 is on the front right (+x, +y), 
# rotor2 is on the rear right, 
# rotor3 is on the front left
# and rotor4 is the pusher motor
# But this could be dangerous for HIL test as it doesn't follow the standard convention
# TODO: we need to fixed the CAD, sdf model

# Front right motor with +z spin
param set-default CA_ROTOR0_CT 100.0000
param set-default CA_ROTOR0_KM 0.0250
param set-default CA_ROTOR0_PX -0.4160
param set-default CA_ROTOR0_PY -0.5040

# Rear left motor with +z spin
param set-default CA_ROTOR1_CT 100.0000
param set-default CA_ROTOR1_KM 0.0250
param set-default CA_ROTOR1_PX 0.4800
param set-default CA_ROTOR1_PY 0.5000

# Front left motor with -z spin
param set-default CA_ROTOR2_CT 100.0000
param set-default CA_ROTOR2_KM -0.0250
param set-default CA_ROTOR2_PX -0.4200
param set-default CA_ROTOR2_PY 0.5000

# Rear right motor with -z spin
param set-default CA_ROTOR3_CT 100.0000
param set-default CA_ROTOR3_KM -0.0250
param set-default CA_ROTOR3_PX 0.4800
param set-default CA_ROTOR3_PY -0.5000

# Pusher motor with +x spin
param set-default CA_ROTOR4_CT 80.0000
param set-default CA_ROTOR4_KM 0.0250
param set-default CA_ROTOR4_PX 1.0260
param set-default CA_ROTOR5_CT 6.5000
param set-default CA_ROTOR5_KM 0.0500
param set-default CA_ROTOR4_AX 1
param set-default CA_ROTOR4_AY 0
param set-default CA_ROTOR4_AZ 0

# ESC parameters (for motors 1-4)
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 10
param set-default SIM_GZ_EC_MAX1 1500
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 10
param set-default SIM_GZ_EC_MAX2 1500
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_MIN3 10
param set-default SIM_GZ_EC_MAX3 1500
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN4 10
param set-default SIM_GZ_EC_MAX4 1500
# motor 5 (pusher motor)
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_MIN5 0
param set-default SIM_GZ_EC_MAX5 3500

param set-default COM_RC_IN_MODE 1

# servos mapping (we have 5 servos: 2 alierion, 2 elevator, 1 rudder)
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204
param set-default SIM_GZ_SV_FUNC5 205
# control surfaces (we have 5: 2 alierion, 2 elevator, 1 rudder)
param set-default CA_SV_CS_COUNT 5
param set-default CA_SV_CS0_TYPE 1 # left aileron, servo_0
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 2 # right aileron, servo_1
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 3 # elevator, servo_2
param set-default CA_SV_CS2_TRQ_P 0.5 # pitch contribution
param set-default CA_SV_CS3_TYPE 3 # elevator, servo_3
param set-default CA_SV_CS3_TRQ_P 0.5 # pitch contribution
param set-default CA_SV_CS4_TYPE 4 # rudder, servo_4
param set-default CA_SV_CS4_TRQ_Y 0.5
# FW controller parameters
param set-default NPFG_PERIOD 12
param set-default FW_PR_FF 0.2
param set-default FW_PR_P 0.9
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MIN -15
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3
param set-default FW_THR_TRIM 0.25
param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2
# MC controller parameters
param set-default MC_AIRMODE 1
param set-default MC_ROLLRATE_P 0.3
param set-default MC_YAW_P 1.6

param set-default MIS_TAKEOFF_ALT 10

param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_P_ACC 3
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_D_ACC 0.1

param set-default NAV_ACC_RAD 5
param set-default NAV_DLL_ACT 2

param set-default VT_FWD_THRUST_EN 4
param set-default VT_PITCH_MIN -5
param set-default VT_F_TRANS_THR 1
param set-default VT_TYPE 2
param set-default FD_ESCS_EN 0

# Battery
param set-default BAT1_N_CELLS 12

# Speed
param set-default FW_AIRSPD_MAX 24.0000
param set-default FW_AIRSPD_MIN 13.0000
param set-default FW_AIRSPD_STALL 10.0000
param set-default FW_AIRSPD_TRIM 18.0000
param set-default FW_SERVICE_CEIL 3000.0000
param set-default VT_ARSP_TRANS 13.0000
param set-default VT_TRANS_TIMEOUT 20.0000

# Weight
param set-default WEIGHT_BASE 11.5000
param set-default WEIGHT_GROSS 11.5000
