#!/bin/sh
#
# @name Generic Standard VTOL
#
# @type Standard VTOL
# @class VTOL

# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
# @board holybro_kakutef7 exclude
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default CA_AIRFRAME 2

param set-default VT_TYPE 2
param set-default MAV_TYPE 22

param set-default RC_CRSF_PRT_CFG 102  # RC receiver (XLRS/CRSF) on TELEM2
param set-default RC_CRSF_TEL_EN 1    # Enable CRSF telemetry

# TODO Check this set before flight
param set-default EKF2_ABL_LIM 0.5
param set-default EKF2_ANGERR_INIT 0.01
param set-default EKF2_GBIAS_INIT 0.01
param set-default EKF2_MAG_TYPE 1
param set-default EKF2_ARSP_THR 10
param set-default EKF2_FUSE_BETA 1
param set-default EKF2_HGT_REF 0 #force baro for HITL (must override any saved value)
param set-default HTE_VXY_THR 2

param set-default SDLOG_DIRS_MAX 7

param set-default NPFG_PERIOD 10

# FW parameters
param set-default FW_AIRSPD_MAX 25
param set-default FW_AIRSPD_MIN 14
param set-default FW_AIRSPD_TRIM 20
param set-default FW_PSP_OFF 0
param set-default FW_P_LIM_MAX 20
param set-default FW_P_LIM_MIN -25
param set-default FW_R_LIM 27
param set-default FW_T_CLMB_MAX 2
param set-default FW_T_CLMB_R_SP 2
param set-default FW_T_SINK_MAX 5
param set-default FW_T_SINK_MIN 2
param set-default FW_PR_FF 0.2
param set-default FW_PR_P 0.6
param set-default FW_PR_D 0.03
param set-default FW_P_RMAX_POS 40
param set-default FW_P_RMAX_NEG 40
param set-default FW_R_RMAX 50
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3
param set-default FW_Y_RMAX 30
param set-default FW_THR_TRIM 0.58 #Check
param set-default FW_THR_MAX 0.75
param set-default FW_THR_MIN 0.05

# MC attitude control
param set-default MC_AIRMODE 1
param set-default MC_ROLL_P 4
param set-default MC_ROLLRATE_K 0.6
param set-default MC_ROLLRATE_MAX 120
param set-default MC_ROLLRATE_P 0.12
param set-default MC_PITCH_P 5
param set-default MC_PITCHRATE_K 0.4
param set-default MC_PITCHRATE_P 0.1
param set-default MC_PITCHRATE_D 0.008
param set-default MC_YAW_P 1.6
param set-default MC_YAWRATE_MAX 30

param set-default MIS_TAKEOFF_ALT 10
param set-default MIS_YAW_TMT 10
param set-default MIS_TKO_LAND_REQ 2

param set-default MPC_ACC_HOR 1
param set-default MPC_ACC_HOR_MAX 1.5
param set-default MPC_ACC_UP_MAX 1.5
param set-default MPC_ALT_MODE 0 #CONFIRM
param set-default MPC_JERK_AUTO 2
param set-default MPC_JERK_MAX 3
param set-default MPC_LAND_ALT2 6
param set-default MPC_LAND_CRWL 0.2
param set-default MPC_LAND_SPEED 0.5
param set-default MPC_MAN_Y_MAX 25
param set-default MPC_THR_MIN 0.1
param set-default MPC_THR_HOVER 0.38
param set-default MPC_TILTMAX_AIR 45
param set-default MPC_VEL_MANUAL 5
param set-default MPC_XY_ERR_MAX 5
param set-default MPC_XY_VEL_MAX 6
param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_P_ACC 3
param set-default MPC_XY_VEL_I_ACC 0.4
param set-default MPC_XY_VEL_D_ACC 0.2
param set-default MPC_YAW_MODE 4
param set-default MPC_Z_VEL_P_ACC 12
param set-default MPC_Z_VEL_I_ACC 3

param set-default NAV_ACC_RAD 5
param set-default NAV_DLL_ACT 2
param set-default NAV_LOITER_RAD 120
param set-default NAV_MC_ALT_RAD 1

param set-default RTL_DESCEND_ALT 10
param set-default RTL_RETURN_ALT 30
param set-default RTL_TYPE 3
param set-default RTL_LOITER_RAD 200
param set-default RTL_MIN_DIST 60

# VTOL transition parameters
param set-default VT_ARSP_BLEND 10
param set-default VT_ARSP_TRANS 13
param set-default VT_B_DEC_MSS 1.5
param set-default VT_FWD_THRUST_EN 4
param set-default VT_F_TRANS_THR 0.85
param set-default VT_F_TRANS_DUR 2
param set-default VT_F_TR_OL_TM 10
param set-default VT_FW_MIN_ALT 20
param set-default VT_PITCH_MIN -5
param set-default VT_QC_T_ALT_LOSS 40
param set-default VT_ELEV_MC_LOCK 1
param set-default VT_TRANS_MIN_TM 5

param set-default WV_EN 1
param set-default WV_YRATE_MAX 25

# Control allocator - VTOL standard

# Rotor configuration (4 MC + 1 pusher)
param set-default CA_ROTOR_COUNT 5

# Front right motor (CCW, -z spin)
param set-default CA_ROTOR0_CT 85.0
param set-default CA_ROTOR0_KM 0.0205
param set-default CA_ROTOR0_PX 0.416
param set-default CA_ROTOR0_PY 0.504

# Rear left motor (CCW, -z spin)
param set-default CA_ROTOR1_CT 85.0
param set-default CA_ROTOR1_KM 0.0205
param set-default CA_ROTOR1_PX -0.48
param set-default CA_ROTOR1_PY -0.50

# Front left motor (CW, +z spin)
param set-default CA_ROTOR2_CT 85.0
param set-default CA_ROTOR2_KM -0.0205
param set-default CA_ROTOR2_PX 0.42
param set-default CA_ROTOR2_PY -0.50

# Rear right motor (CW, +z spin)
param set-default CA_ROTOR3_CT 85.0
param set-default CA_ROTOR3_KM -0.0205
param set-default CA_ROTOR3_PX -0.48
param set-default CA_ROTOR3_PY 0.50

# Pusher motor (+x thrust axis)
param set-default CA_ROTOR4_CT 80.0
param set-default CA_ROTOR4_KM 0.0281
param set-default CA_ROTOR4_PX -1.026
param set-default CA_ROTOR4_AX 1
param set-default CA_ROTOR4_AY 0
param set-default CA_ROTOR4_AZ 0

# Control surface configuration (5 surfaces)
param set-default CA_SV_CS_COUNT 5

# Left aileron
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5

# Right aileron
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS1_TRQ_R 0.5

# Right elevator
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS2_TRQ_P -1

# Left elevator
param set-default CA_SV_CS3_TYPE 3
param set-default CA_SV_CS3_TRQ_P 1

# Rudder
param set-default CA_SV_CS4_TYPE 4
param set-default CA_SV_CS4_TRQ_Y 1

# PWM outputs
param set PWM_MAIN_FUNC1 201
param set PWM_MAIN_FUNC2 202
param set PWM_MAIN_FUNC3 203
param set PWM_MAIN_FUNC4 204
param set PWM_MAIN_FUNC5 205

param set PWM_MAIN_DIS1 1440
param set PWM_MAIN_DIS2 1570
param set PWM_MAIN_DIS3 1470
param set PWM_MAIN_DIS4 1570
param set PWM_MAIN_DIS5 1460

param set PWM_MAIN_MAX1 1850
param set PWM_MAIN_MAX2 1960
param set PWM_MAIN_MAX3 1760
param set PWM_MAIN_MAX4 1890
param set PWM_MAIN_MAX5 1960
param set PWM_MAIN_MIN1 1070
param set PWM_MAIN_MIN2 1170
param set PWM_MAIN_MIN3 1150
param set PWM_MAIN_MIN4 1240
param set PWM_MAIN_MIN5 1130

# Enable HITL mode
param set-default SYS_HITL 0
param set SYS_HITL 0

# Enable real actuator output during HITL
# WARNING: Motors will spin! Remove propellers for safety!
param set HIL_ACT_REAL 0

# Keep UAVCAN enabled for real motor output (do NOT disable like other .hil files)
param set UAVCAN_ENABLE 3

# UAVCAN ESC function mapping (Motor 1-5)
# Maps UAVCAN ESC nodes to actuator functions for ESC telemetry
param set UAVCAN_EC_FUNC1 101
param set UAVCAN_EC_FUNC2 102
param set UAVCAN_EC_FUNC3 103
param set UAVCAN_EC_FUNC4 104
param set UAVCAN_EC_FUNC5 105

param set-default FD_ACT_EN 1
param set-default FD_ESCS_EN 1
param set-default FD_ACT_MOT_TOUT 500

param set-default COM_PREARM_MODE 2
param set-default COM_OBL_RC_ACT 3
param set-default COM_RCL_EXCEPT 7
param set-default COM_RC_IN_MODE 2 #rc or mavlink (joystick)
param set-default COM_RC_STICK_OV 15
param set-default COM_FLTMODE1 2 #POSITION
param set-default COM_FLTMODE4 3 #OFFBOARD
param set-default COM_FLTMODE6 7 #MISSION

param set-default RC_MAP_FLTMODE 6 #Channel 6
param set-default RC_MAP_KILL_SW 8 #Channel 8

# Airspeed sensor enabled (required for VTOL fixed-wing flight)
param set-default SYS_HAS_NUM_ASPD 1
param set-default ASPD_DO_CHECKS 7

param set-default SDLOG_PROFILE 3 #3=System Identification

# Battery
param set-default BAT1_SOURCE 1
param set-default BAT1_CAPACITY 22000
param set-default BAT1_N_CELLS 12

# Geofence
param set-default GF_ACTION 3
param set-default GF_MAX_HOR_DIST 5000
param set-default GF_MAX_VER_DIST 150

# Offboard
param set-default UXRCE_DDS_CFG 103
param set-default SER_TEL3_BAUD 921600

# UAVCAN sensors
param set-default UAVCAN_NODE_ID 15
param set-default UAVCAN_SUB_ASPD 1
param set-default UAVCAN_SUB_DPRES 1
param set-default UAVCAN_SUB_BAT 2

param set-default MAN_ARM_GESTURE 0 #disable arming with throttle/yaw stick

